vich_uploader:
    db_driver: orm

    mappings:
        user:
            uri_prefix: /uploads/img
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        parameters:
            uri_prefix: /uploads/parameters
            upload_destination: '%kernel.project_dir%/public/uploads/parameters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        reporting:
            uri_prefix: /uploads/reporting
            upload_destination: '%kernel.project_dir%/public/uploads/reporting'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
