vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        config_file:
            uri_prefix: /uploads/config_file
            upload_destination: '%kernel.project_dir%/public/uploads/config_file'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
